import type { Match, Standing, User, Prediction, BonusPoint } from '@/types'

const NOW = new Date()
function past(days: number): string { const d=new Date(NOW); d.setDate(d.getDate()-days); return d.toISOString() }
function future(days: number, hours=20): string { const d=new Date(NOW); d.setDate(d.getDate()+days); d.setHours(hours,0,0,0); return d.toISOString() }

export const MOCK_USERS: User[] = [
  { id:'u1', nick:'admin', role:'admin', status:'active', total_points:47, match_points:38, bonus_points:9, predictions_count:14, correct_outcomes:10, correct_scores:3, current_streak:3, best_streak:5, tournament_winner_pick:'br', form_effect_override:'auto', custom_form_title:null, admin_note:null, created_at:past(30) },
  { id:'u2', nick:'Dawid', role:'user', status:'active', total_points:42, match_points:36, bonus_points:6, predictions_count:14, correct_outcomes:9, correct_scores:2, current_streak:1, best_streak:4, tournament_winner_pick:'fr', form_effect_override:'auto', custom_form_title:null, admin_note:null, created_at:past(30) },
  { id:'u3', nick:'Flickswagen', role:'user', status:'active', total_points:39, match_points:33, bonus_points:6, predictions_count:13, correct_outcomes:8, correct_scores:2, current_streak:0, best_streak:3, tournament_winner_pick:'de', form_effect_override:'auto', custom_form_title:null, admin_note:null, created_at:past(30) },
  { id:'u4', nick:'Typer4', role:'user', status:'active', total_points:31, match_points:28, bonus_points:3, predictions_count:12, correct_outcomes:7, correct_scores:1, current_streak:2, best_streak:3, tournament_winner_pick:'ar', form_effect_override:'auto', custom_form_title:null, admin_note:null, created_at:past(30) },
  { id:'u5', nick:'Typer5', role:'user', status:'pending', total_points:0, match_points:0, bonus_points:0, predictions_count:0, correct_outcomes:0, correct_scores:0, current_streak:0, best_streak:0, tournament_winner_pick:null, form_effect_override:'auto', custom_form_title:null, admin_note:null, created_at:past(10) },
]

export const MOCK_MATCHES: Match[] = [
  { id:'m1', api_id:'api_001', phase:'group', group_name:'A', round:1, match_date:past(5), stadium:'SoFi Stadium', city:'Los Angeles', team_a:'Meksyk', team_b:'Polska', team_a_code:'mx', team_b_code:'pl', status:'finished', score_a:2, score_b:1, halftime_a:1, halftime_b:0, data_source:'mock', last_synced_at:past(5), created_at:past(30), events:[{minute:23,type:'goal',team:'home',player:'H. Lozano'},{minute:67,type:'goal',team:'home',player:'R. Jimenez'},{minute:80,type:'goal',team:'away',player:'R. Lewandowski'},{minute:45,type:'yellow_card',team:'away',player:'G. Zieliński'}], stats:{possession_home:48,possession_away:52,shots_home:12,shots_away:14,shots_on_target_home:4,shots_on_target_away:5,corners_home:4,corners_away:6,fouls_home:11,fouls_away:13,yellow_cards_home:1,yellow_cards_away:2,red_cards_home:0,red_cards_away:0} },
  { id:'m2', api_id:'api_002', phase:'group', group_name:'A', round:1, match_date:past(5), stadium:'MetLife Stadium', city:'New York', team_a:'Argentyna', team_b:'Francja', team_a_code:'ar', team_b_code:'fr', status:'finished', score_a:3, score_b:2, halftime_a:1, halftime_b:1, data_source:'mock', last_synced_at:past(5), created_at:past(30), events:[{minute:32,type:'goal',team:'home',player:'L. Messi'},{minute:41,type:'goal',team:'away',player:'K. Mbappé'},{minute:55,type:'goal',team:'home',player:'J. Álvarez'},{minute:73,type:'goal',team:'away',player:'O. Dembélé'},{minute:88,type:'goal',team:'home',player:'Á. Di María'}], stats:{possession_home:44,possession_away:56,shots_home:10,shots_away:18,shots_on_target_home:5,shots_on_target_away:7,corners_home:3,corners_away:8,fouls_home:14,fouls_away:10,yellow_cards_home:2,yellow_cards_away:1,red_cards_home:0,red_cards_away:0} },
  { id:'m3', api_id:'api_003', phase:'group', group_name:'B', round:1, match_date:past(4), stadium:'AT&T Stadium', city:'Dallas', team_a:'Brazylia', team_b:'Niemcy', team_a_code:'br', team_b_code:'de', status:'finished', score_a:0, score_b:0, halftime_a:0, halftime_b:0, data_source:'mock', last_synced_at:past(4), created_at:past(30), events:[{minute:34,type:'yellow_card',team:'home',player:'Casemiro'},{minute:78,type:'yellow_card',team:'away',player:'T. Müller'}], stats:{possession_home:53,possession_away:47,shots_home:9,shots_away:8,shots_on_target_home:2,shots_on_target_away:2,corners_home:5,corners_away:4,fouls_home:12,fouls_away:10,yellow_cards_home:1,yellow_cards_away:1,red_cards_home:0,red_cards_away:0} },
  { id:'m4', api_id:'api_004', phase:'group', group_name:'B', round:1, match_date:past(3), stadium:"Levi's Stadium", city:'San Francisco', team_a:'Anglia', team_b:'Japonia', team_a_code:'gb', team_b_code:'jp', status:'finished', score_a:1, score_b:1, halftime_a:0, halftime_b:1, data_source:'mock', last_synced_at:past(3), created_at:past(30), events:[{minute:38,type:'goal',team:'away',player:'D. Kamada'},{minute:65,type:'goal',team:'home',player:'H. Kane'}], stats:{possession_home:60,possession_away:40,shots_home:16,shots_away:7,shots_on_target_home:4,shots_on_target_away:3,corners_home:7,corners_away:2,fouls_home:8,fouls_away:14,yellow_cards_home:1,yellow_cards_away:3,red_cards_home:0,red_cards_away:0} },
  { id:'m5', api_id:'api_005', phase:'group', group_name:'C', round:1, match_date:past(0), stadium:'Rose Bowl', city:'Los Angeles', team_a:'Hiszpania', team_b:'Portugalia', team_a_code:'es', team_b_code:'pt', status:'live', score_a:1, score_b:0, halftime_a:1, halftime_b:0, data_source:'mock', last_synced_at:new Date().toISOString(), created_at:past(30) },
  { id:'m6', api_id:'api_006', phase:'group', group_name:'C', round:1, match_date:future(1), stadium:'Mercedes-Benz Stadium', city:'Atlanta', team_a:'Włochy', team_b:'Holandia', team_a_code:'it', team_b_code:'nl', status:'scheduled', score_a:null, score_b:null, halftime_a:null, halftime_b:null, data_source:'mock', last_synced_at:null, created_at:past(30) },
  { id:'m7', api_id:'api_007', phase:'group', group_name:'D', round:1, match_date:future(2,18), stadium:'Hard Rock Stadium', city:'Miami', team_a:'USA', team_b:'Kanada', team_a_code:'us', team_b_code:'ca', status:'scheduled', score_a:null, score_b:null, halftime_a:null, halftime_b:null, data_source:'mock', last_synced_at:null, created_at:past(30) },
  { id:'m8', api_id:'api_008', phase:'group', group_name:'D', round:1, match_date:future(2,21), stadium:'Estadio Azteca', city:'Mexico City', team_a:'Maroko', team_b:'Senegal', team_a_code:'ma', team_b_code:'sn', status:'scheduled', score_a:null, score_b:null, halftime_a:null, halftime_b:null, data_source:'mock', last_synced_at:null, created_at:past(30) },
  { id:'m9', api_id:'api_009', phase:'group', group_name:'A', round:2, match_date:future(5), stadium:'BC Place', city:'Vancouver', team_a:'Polska', team_b:'Argentyna', team_a_code:'pl', team_b_code:'ar', status:'scheduled', score_a:null, score_b:null, halftime_a:null, halftime_b:null, data_source:'mock', last_synced_at:null, created_at:past(30) },
  { id:'m10', api_id:'api_010', phase:'group', group_name:'A', round:2, match_date:future(5,22), stadium:'Empower Field', city:'Denver', team_a:'Meksyk', team_b:'Francja', team_a_code:'mx', team_b_code:'fr', status:'scheduled', score_a:null, score_b:null, halftime_a:null, halftime_b:null, data_source:'mock', last_synced_at:null, created_at:past(30) },
  { id:'m11', api_id:'api_011', phase:'round_of_16', group_name:null, round:1, match_date:future(20,18), stadium:'MetLife Stadium', city:'New York', team_a:'', team_b:'', team_a_code:'', team_b_code:'', home_placeholder:'Lider Gr. A', away_placeholder:'2. miejsce Gr. B', status:'scheduled', score_a:null, score_b:null, halftime_a:null, halftime_b:null, data_source:'mock', last_synced_at:null, created_at:past(30) },
  { id:'m12', api_id:'api_012', phase:'round_of_16', group_name:null, round:1, match_date:future(20,21), stadium:'SoFi Stadium', city:'Los Angeles', team_a:'', team_b:'', team_a_code:'', team_b_code:'', home_placeholder:'Lider Gr. C', away_placeholder:'2. miejsce Gr. D', status:'scheduled', score_a:null, score_b:null, halftime_a:null, halftime_b:null, data_source:'mock', last_synced_at:null, created_at:past(30) },
  { id:'m13', api_id:'api_013', phase:'quarterfinal', group_name:null, round:1, match_date:future(25,18), stadium:'AT&T Stadium', city:'Dallas', team_a:'', team_b:'', team_a_code:'', team_b_code:'', home_placeholder:'Zwycięzca M11', away_placeholder:'Zwycięzca M12', status:'scheduled', score_a:null, score_b:null, halftime_a:null, halftime_b:null, data_source:'mock', last_synced_at:null, created_at:past(30) },
  { id:'m14', api_id:'api_014', phase:'semifinal', group_name:null, round:1, match_date:future(30,20), stadium:'Hard Rock Stadium', city:'Miami', team_a:'', team_b:'', team_a_code:'', team_b_code:'', home_placeholder:'Zwycięzca ćwierćfinału 1', away_placeholder:'Zwycięzca ćwierćfinału 2', status:'scheduled', score_a:null, score_b:null, halftime_a:null, halftime_b:null, data_source:'mock', last_synced_at:null, created_at:past(30) },
  { id:'m15', api_id:'api_015', phase:'final', group_name:null, round:1, match_date:future(35,20), stadium:'MetLife Stadium', city:'New York', team_a:'', team_b:'', team_a_code:'', team_b_code:'', home_placeholder:'Zwycięzca półfinału 1', away_placeholder:'Zwycięzca półfinału 2', status:'scheduled', score_a:null, score_b:null, halftime_a:null, halftime_b:null, data_source:'mock', last_synced_at:null, created_at:past(30) },
]

export const MOCK_STANDINGS: Standing[] = [
  { id:'s1', group_name:'A', team:'Argentyna', team_code:'ar', played:1, won:1, drawn:0, lost:0, goals_for:3, goals_against:2, goal_difference:1, points:3, position:1, updated_at:past(5) },
  { id:'s2', group_name:'A', team:'Meksyk', team_code:'mx', played:1, won:1, drawn:0, lost:0, goals_for:2, goals_against:1, goal_difference:1, points:3, position:2, updated_at:past(5) },
  { id:'s3', group_name:'A', team:'Polska', team_code:'pl', played:1, won:0, drawn:0, lost:1, goals_for:1, goals_against:2, goal_difference:-1, points:0, position:3, updated_at:past(5) },
  { id:'s4', group_name:'A', team:'Francja', team_code:'fr', played:1, won:0, drawn:0, lost:1, goals_for:2, goals_against:3, goal_difference:-1, points:0, position:4, updated_at:past(5) },
  { id:'s5', group_name:'B', team:'Brazylia', team_code:'br', played:1, won:0, drawn:1, lost:0, goals_for:0, goals_against:0, goal_difference:0, points:1, position:1, updated_at:past(4) },
  { id:'s6', group_name:'B', team:'Niemcy', team_code:'de', played:1, won:0, drawn:1, lost:0, goals_for:0, goals_against:0, goal_difference:0, points:1, position:2, updated_at:past(4) },
  { id:'s7', group_name:'B', team:'Anglia', team_code:'gb', played:1, won:0, drawn:1, lost:0, goals_for:1, goals_against:1, goal_difference:0, points:1, position:3, updated_at:past(3) },
  { id:'s8', group_name:'B', team:'Japonia', team_code:'jp', played:1, won:0, drawn:1, lost:0, goals_for:1, goals_against:1, goal_difference:0, points:1, position:4, updated_at:past(3) },
]

export const MOCK_PREDICTIONS: Prediction[] = [
  { id:'p1', user_id:'u1', match_id:'m1', predicted_a:2, predicted_b:1, predicted_result:'home', points_earned:8, is_correct_outcome:true, is_correct_score:true, is_locked:true, created_at:past(6), updated_at:past(6) },
  { id:'p2', user_id:'u2', match_id:'m1', predicted_a:1, predicted_b:0, predicted_result:'home', points_earned:3, is_correct_outcome:true, is_correct_score:false, is_locked:true, created_at:past(6), updated_at:past(6) },
  { id:'p3', user_id:'u3', match_id:'m1', predicted_a:1, predicted_b:1, predicted_result:'draw', points_earned:0, is_correct_outcome:false, is_correct_score:false, is_locked:true, created_at:past(6), updated_at:past(6) },
  { id:'p4', user_id:'u1', match_id:'m2', predicted_a:3, predicted_b:2, predicted_result:'home', points_earned:8, is_correct_outcome:true, is_correct_score:true, is_locked:true, created_at:past(6), updated_at:past(6) },
  { id:'p5', user_id:'u2', match_id:'m2', predicted_a:2, predicted_b:1, predicted_result:'home', points_earned:3, is_correct_outcome:true, is_correct_score:false, is_locked:true, created_at:past(6), updated_at:past(6) },
  { id:'p6', user_id:'u3', match_id:'m2', predicted_a:1, predicted_b:2, predicted_result:'away', points_earned:0, is_correct_outcome:false, is_correct_score:false, is_locked:true, created_at:past(6), updated_at:past(6) },
  { id:'p7', user_id:'u1', match_id:'m5', predicted_a:2, predicted_b:0, predicted_result:'home', points_earned:0, is_correct_outcome:false, is_correct_score:false, is_locked:false, created_at:past(1), updated_at:past(1) },
  { id:'p8', user_id:'u2', match_id:'m5', predicted_a:1, predicted_b:0, predicted_result:'home', points_earned:0, is_correct_outcome:false, is_correct_score:false, is_locked:false, created_at:past(1), updated_at:past(1) },
]

export const MOCK_BONUS_POINTS: BonusPoint[] = [
  { id:'b1', user_id:'u1', match_id:null, round:1, bonus_type:'round_king', points:3, description:'Król kolejki 1', created_at:past(4) },
  { id:'b2', user_id:'u1', match_id:'m1', round:null, bonus_type:'risky_pick', points:2, description:'Jedyny trafiony dokładny wynik', created_at:past(5) },
  { id:'b3', user_id:'u2', match_id:null, round:1, bonus_type:'streak_3', points:2, description:'Seria 3 trafień z rzędu', created_at:past(4) },
  { id:'b4', user_id:'u3', match_id:null, round:1, bonus_type:'round_king', points:3, description:'Król kolejki 1', created_at:past(4) },
]
